package dev.lajoscseppento.fancydoc.example;

/** Example library, generated by Gradle. */
public class Library {
  /**
   * Example method.
   *
   * @return always {@code true}
   */
  public boolean someLibraryMethod() {
    return true;
  }
}
